def boy(st):
    print("\n\n")
    if st==0:
        print("************************")
        print("*                      *")
        print("*       _______        *")
        print("*              |       *")
        print("*              |       *")
        print("*              |       *")
        print("*              |       *")
        print("*              |       *")
        print("*              |       *")
        print("*  ____________|       *")
        print("*                      *")
        print("************************")
    elif st==1:
        print("************************")
        print("*                      *")
        print("*       _______        *")
        print("*       |      |       *")
        print("*              |       *")
        print("*              |       *")
        print("*              |       *")
        print("*              |       *")
        print("*              |       *")
        print("*  ____________|       *")
        print("*                      *")
        print("************************")
    elif st==2:
        print("************************")
        print("*                      *")
        print("*       _______        *")
        print("*       |      |       *")
        print("*       0      |       *")
        print("*              |       *")
        print("*              |       *")
        print("*              |       *")
        print("*              |       *")
        print("*  ____________|       *")
        print("*                      *")
        print("************************")
    elif st==3:
        print("************************")
        print("*                      *")
        print("*       _______        *")
        print("*       |      |       *")
        print("*       0      |       *")
        print("*      /|\     |       *")
        print("*              |       *")
        print("*              |       *")
        print("*              |       *")
        print("*  ____________|       *")
        print("*                      *")
        print("************************")
    elif st==4:
        print("************************")
        print("*                      *")
        print("*       _______        *")
        print("*       |      |       *")
        print("*       0      |       *")
        print("*      /|\     |       *")
        print("*       |      |       *")
        print("*              |       *")
        print("*              |       *")
        print("*  ____________|       *")
        print("*                      *")
        print("************************")
    elif st==5:
        print("************************")
        print("*                      *")
        print("*       _______        *")
        print("*       |      |       *")
        print("*       0      |       *")
        print("*      /|\     |       *")
        print("*       |      |       *")
        print("*      / \     |       *")
        print("*              |       *")
        print("*  ____________|       *")
        print("*                      *")
        print("************************")
    else:
        print("************************")
        print("*                      *")
        print("*       _______        *")
        print("*       |      |       *")
        print("*       0      |       *")
        print("*      /|\     |       *")
        print("*       |      |       *")
        print("*      / \     |       *")
        print("*              |       *")
        print("*  ____________|       *")
        print("*                      *")
        print("************************")